### ISSUE TITLE
A|B: Polish 

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1118]
### Description

Once the major components of the A|B feature have been implemented there will be a number of minor pieces to _polish_ or implement. 

**More detail**:
* Fix components that were disabled or broken during implementation
* Add styles/features and other functionality that has been skipped
* Fix components that were disabled or broken during implementation. 
* Clean up vast amount of code added for this feature 
  * Adding comments
  * Eliminate duplicate code
  * Make code as performant and scalable as possible

### Todos

More time consuming:
- [x] Add legends
- [x] running-data capability
- [x] Add zots
- [x] Timeline layer preview to reflect active `A|B` state
- [x] custom colormaps
- [x] Make sidebar hide/show button work
- [x] Enable layer Drag capability 
- [x] Integrate w/ Events
- [x] Integrate w/ data download
- [x] Make App still work when `A|B` is disabled in options
- [x] Add comments to code

Less time consuming:
- [x] Dateline text missing
- [x] Use context instead of `prop drilling` for relevant react-components
- [x] disable `A|B` for mobile
- [x] fix broken animation draggers
- [x] 2 layer-states instead of 3
- [x] Use correct layers when projection changes
- [x] Wait to load initial A|B state when the compare button is first touched as opposed to on load 
- [x] Create reverse swiping to fix clear selections
- [x] Style sidebar tabs and buttons
- [x] highlight layers in timeline when hovered in sidebar
- [x] Disable `snapshot`, `Events`, `Data` & `animation`  when in A|B
- [x] Add compare mode labels
- [x] Resize sidebar based on height
- [x] Add icons to buttons in sidebar
- [x] add google analytics
- [x] Update only the layergroup that needs to be updated on date change
- [x] start tour should exit A|B
- [x] Keep swipe line in viewport
- [x] Permalink to only retain `A|B` state if `A|B` is active
- [x] Update layers in sidebar and layer-list when projection changes
- [x] Add correct styling to timeline picks
- [x] Fix graticule bug (they are applied differently than other layers and need to be accounted for)
- [x] Set Opacity of Of individual layers (With layer options panel when `A|B` is active)
- [x] When changing dates with date-selector map doesn't update correctly 
- [x] Disable layers that do not have imagery available
- [x] Dual Legend bug (show min/max on non-running legend)
- [x] style scrollbar
- [x] Isolate sidebar footer
- [x] Make work with subdaily
- [x] left/right-arrow-group disable/enable not updating
- [x] fix `Cannot read property 'startDate' of undefined` on layer updates (happens when removing layers)
- [x] Allow setting of opacity for graticules #1156 
- [x] ~~Apply swipe, spy, and opacity to graticules if possible~~ (Not for initial release #1158 )
- [x] Pull `worldview-components` repo code into core repo
- [x] Fix css linting errors that are breaking build
- [x]  `Unsupported nested scroll container detected.`
- [x] Replace `getActiveLayerGroupString` method with `model.layers.activeLayers`
- [x] fix palette thresholds 
- [x] animation breaking
- [x] Map not inheriting layer-group B's layers when exiting compare mode
- [x] Fix legend running off palette
- [x] Zots not showing up
- [x] Aerosol Optical Depth Average (Green, Monthly) running data value not being offset
- [x] left-right time changer doesn't update correctly when in `B` mode
- [x] when dragging the time slider in comparison mode, there is no visual feedback of the date under the guitar pick
- [x] make date start with a 1 day difference instead of 5
- [x] Inactive pick should be clickable
- [x] Save draggers position in permalink
- [x] Opacity slider handle covers "A" or "B" if dragged to either end
- [x] Opacity slider "should be bigger with an easier handle to grab"
- [x] when in spyglass mode and switching "A" and "B" tabs, the "A" or "B" label shows up on the map by itself
- [x] Slider to drag with touch devices
- [x] Only re-render layers when necessary
  * ~~When changing from `A` -> `B` the map only needs to re-render in spy mode~~
  *  ~~On Date change, only re-render the layerGroup that is being updated~~
  * ~~On Layer Add/Remove just add/remove what is needed~~
- [x] Prevent swiper from swiping labels off screen
- [x] fix js linting errors
- [x] Fix buster errors (or just remove failing tests since we plan to move away from these?)
- [x] should be able to deactivate Events && Data download  in options
- [ ] `A` label is getting stuck in top-corner in spy mode
- [x] Make swipe dragger larger
- [x] fix animation which was broken by merge

IE

- [x] Not swiping
- [x] map not updating after mode/layer-state switch
- [x] opacity input-swiper styling
- [x] Hover over scale-legend
