### ISSUE TITLE
Webpack build enhancements

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1186]
Future enhancements to clean up/optimize Webpack build and reduce unnecessary imports in code base.

- [x] remove individual jquery imports, and investigate other packages to remove
- [x] add eslint jquery rule
- [x] test global jquery options in build and potentially remove ProvidePlugin
- [x] limit environmental variables to conventional standards
- [x] clean up npm scripts for most consistency using crossenv, NODE_ENV, and potentially use --mode
- [x] reduce CSS build size
- [x] Add cssnext, a postcss plugin #923
- [x] Rework font-awesome inclusion #1375 
- [x] Import fontawesome fonts independently #2684

**Comment by ZachTRice** [comment]
Added changing jquery-ui-bundle into individual imports which wasn't possible with the non-webpack build

**Comment by ZachTRice** [comment]
We should find a way to only output the font-awesome icons that are needed. The latest webpack build injects every FA4 icon into a style tag in the head.
