### ISSUE TITLE
Fix broken E2E tests

### ISSUE THREAD

**Issue by Benjaki2** [nasa-gibs/worldview#1564]
**Describe the bug**
Fix broken `E2E` tests mostly caused by recent updates
- [x] `e2e` tests still test for separate `notification` and `message` buttons in info updated by #904
- [x] GIF selections broken by font awesome migration #1375 
- [x] Use mock with event test that tests if link opens new tab so that it doesn't sometimes download data instead of opening in a new tab
- [x] Options panel fixes #375 
- [x] Layer picker fixes
