### ISSUE TITLE
Epic - Tour v1.1 potential feature enhancements

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#1613]
This ticket is to track future enhancements to the tour feature.

New Features:

- [x]  Add a way for users to access tours that are not shown in the 9 featured startups.

Step transitions/actions:
- [ ]  Add ability to turn map animation on / off
- [ ]  Optimize animation after a "fly" event to improve animation precache. 
- [ ]  Optimize animation pause causing the wrong day being selected after animation has ran on previous step. Currently mitigated by adding an additional step after animation plays to "re-pause" the animation.
- [ ]  Create an "auto play mode"; this would perhaps satisfy issue https://github.com/nasa-gibs/worldview/issues/284

Step transitions/actions (2/7 Dev Meeting):
- [x]  Consider ability to show icons in the story text and/or be able highlight certain widgets
- [x]  Consider ability to “point” to the map itself (e.g., to the pine island glacier story)
- [ ]  Consider ability for storyteller to choose “bounce/transition” speed
- [x]  Still some issues when you move from a step that’s playing an animation and it’s near the end of the animation and you go to the next step, it’ll keep the date that you ended on with the animation. 

Miscellaneous: 
- [ ]  Add all step markdown files into 1 file that is split into separate html files on build
- [x]  Change default width to four columns (if browser width permits) in order to display more stories at once with continuing availability of older stories. (10/3 Dev Meeting)

**Comment by edplato** [comment]
Add orbit tracks to the general application tutorial and possibly feature in a story to address #1405.

**Comment by ZachTRice** [comment]
Per our stand-up discussion:
Add a way for users to access tours that are not shown in the 9 featured startups. 

Possible Solutions:
- An additional pop-up with links (linked from startup modal or info toolbar)
- Paginate boxes page (9 per pagination)
- Scroll to see more thumbnails*

*Note:
The tour was designed so that if we decided to later, we could increase the number and allow users to scroll further down, we discussed it briefly but decided to just have 9 featured in the end.
see: https://github.com/nasa-gibs/worldview/blob/master/web/js/components/tour/tour-boxes.js#L11

**Comment by ZachTRice** [comment]
PR #2080 implements the feature request to view previous tours

**Comment by minniewong** [comment]
Consider: https://github.com/gilbarbara/react-joyride

**Comment by minniewong** [comment]
Issues have not been disruptive since this epic was written. Will close ticket for now, and open others as we see fit.
