### ISSUE TITLE
Epic - Timeline Enhancements v1.1

### ISSUE THREAD

**Issue by edplato** [nasa-gibs/worldview#1776]
This ticket is to track future enhancements to the timeline capabilities - some idea/UI designs can be seen in in #1496 .

- [x] Add data availability bars #1772 
- [x] More relaxed date text input #1662
- [x] Timeline pan with dragger at edge of visible axis #2579 
- [x] If custom widget open and no selection made, select previous interval rather than prevent left/right arrow date change
