### ISSUE TITLE
Initial vector support implementation

### ISSUE THREAD

**Issue by minniewong** [nasa-gibs/worldview#556]
- [x] Create dedicated vector-support branch with latest WV 2.0 changes for testing
- [x] Implemented static OL methods to pull in vector tiles from SIT (or local) source
** This means converting from old local onEarth WMS format to WMTS based
- [x] Upgrade OpenLayers to 4.4.x+ to prevent rendering bugs and use latest vector features.
Pending Fix in https://github.com/nasa-gibs/worldview/pull/722
- [x] Investigate time-related issue (Possibly GC related) where layer is showing as available in dates where it shouldn't be. Note: this was fixed by adding `inactive: true` flag to the layer json.
- [x] Investigate why over-zoom indicator is showing incorrectly. Note: this was fixed by implementing the correct oltilegrid method and variables.
- [x] Investigate console errors related to FIRMS_MODIS_vs layer only. 404 cross-origin; Moved to seperate issue #733 "Investigate better 404 error handling with Vector Tiles" for a decision to made pre-production launch. 
- [x] #559 (Support style options for vector layers)
- [x] Create dynamic (production ready) method to pull in vector tiles (comes after implementing #559)
- [x] Support laser beam tracks for ICESat-2 support mission

Possibly need to:
Create method to support a WMS based Vector Tile implementation. (Would be similiar to how I was serving local onEarth tiles previously).

Future:
Investigate integrating LERC-type layers (dependent on GIBS providing data)

See also related Issues:
https://github.com/nasa-gibs/worldview/issues/559 - Support style options for vector layers
https://github.com/nasa-gibs/worldview/issues/561 - Expand layer debug tools to include vector layer specific data
https://github.com/nasa-gibs/worldview/issues/560 - Create vector point tooltips

**Comment by ZachTRice** [comment]
Resources related to vector layers:
LERC Resources
- https://github.com/anvaka/fieldplay
- https://github.com/Esri/lerc & http://esri.github.io/lerc/ & https://developers.arcgis.com/javascript/3/samples/layers_imageservicevector/ & https://developers.arcgis.com/javascript/3/samples/layers_raster/
- https://earth.nullschool.net & https://github.com/cambecc/earth
which is based on..
- https://github.com/cambecc/air & https://air.nullschool.net/

Other layer styling resources (Not necessarily vector related but could have some x-over): 
WebGL Libraries I am looking at using for rasters: 
- https://github.com/phoboslab/WebGLImageFilter & https://github.com/evanw/glfx.js (For basic colors)
- https://github.com/santilland/plotty (For color palettes)

**Comment by ZachTRice** [comment]
Possible LERC Layer implementations (From OnEarth talk).
Also see OnEarth JIRA ticket related to on going work / discussions.
- GeoJson file with pixel arrays.
- Requesting two vector tiles (PBF/MVT) to build pixel array.

**Comment by ZachTRice** [comment]
I pushed up a branch with the vector changes merged in with the latest 2.0 release.
https://github.com/nasa-gibs/worldview/tree/vector-support-2.0

To build with the GIBS options repo you will need to run: 
`IGNORE_ERRORS=true npm run build -- subdirectory_name` 
To run just a GC fetech or GC config separately run:
`IGNORE_ERRORS=true npm run updateconfig -- subdirectory_name`- fetch
`IGNORE_ERRORS=true npm run build:config -- subdirectory_name` - config

There is also a branch based on WV v1.5:
https://github.com/nasa-gibs/worldview/tree/vector-support

**Comment by ZachTRice** [comment]
@mcechini please review current progress and provide feedback as necessary.
