### ISSUE TITLE
Create mapbox-styles for vector layers

### ISSUE THREAD

**Issue by ZachTRice** [nasa-gibs/worldview#559]
**Phase 2**
To Do:
- [x] Create a default FIRMS MapBox Style JSON 
- [x] Create customized FIRMS style JSON (Based on confidence or FRP)
- [x] Create a default Orbit Tracks MapBox Style JSON 
- [x] Create customized Orbit Tracks style JSON
- [x] Create a default Sedac MapBox Style JSON 
- [ ] Create customized Sedac style JSON
---------------
**Phase 1**
To Do:
- [x] Create static method to add default vector style
- [x] Create static method to color vectors based on MVT features 
- [x] Create a standard JSON style file to set default / advanced color options (with GIBS supporting)
- [x] Create build step in `extractConfigFromWMTS.py` to detect mapbox-gl-style in xlink:role & add a reference to it in the layer within the wv.json config.
- [x] Create build step in `validateOptions.py` to pull in the remote JSON file and add it to `build/options/config/palettes` which then gets moved (along with the other converted colormap to JSON files) into `web/config/palettes`.
- [x] Implement base styles based on the JSON file.
- [x] Create styleCache object for caching styles per feature.
- [x] Implement styles per feature dynamically based on the JSON file using vectorStyle object

Other considerations
- Zoom level scaling support:
Implement method to change styling on the fly based on zoom level. This can go hand-in-hand with a mapbox-gl-style specification document which would have style info included for different zoom levels.
- [Support a default set of styles based on unique layer features (i.e. arrows for wind direction, confidence for fires, etc.) 

Objective:
Layers should include a default style based on feature or type. In the sidebar options modal, there should be an option to change features based on common layer attributes. The default feature styling could be how the layer image is styled when using image-download.

Example / Ideas: 
Wind / Ocean Current layers: Direction + Speed: Arrows / animation pointing the user in the right direction and animation to demonstrate varying speeds
Fire layers: Confidence: 3 colors based on confidence

**Comment by mcechini** [comment]
Per our discussion, here's a "schema" of sorts for the contents of our intermediate JSON styles that will 
be referenced in the Capabilities document for an MVT layer:

`
{
  "styles": [
    { 
      "name"      : "Human readable description",
      "property"  : "MVT Tag Name"
      "values"    : [ "Value 1", "Value 2" ],
      "range"     : "[min,max)"
      "regex"     : "^...$"
      "label"     : { "property":"label", "stroke_color":"rgb(128,128,128)", "fill_color":"rgb(255,255,255)" }, "size":7.5 }
      "points"    : { "color":"xxx,xxx,xxx", "radius":5 }
      "lines"     : { "color":"xxx,xxx,xxx", "width":5 }
      "polygons"  : { "stroke_color":"xxx,xxx,xxx", "stroke_width":5, "fill_color":"xxx,xxx,xxx" } 
    },
  ]
}
`

- The "range", "values", and "regex" elements are mutually exclusive options
- The "label" element is optional
- If the "fill_color" is missing in the "polygons" element, then assume a transparent fill

A style JSON will contain multiple "styles" entries.  Worldview will iterate through the 
styles looking for a match to a MVT feature.  If a match is found, the style is applied.
If no match is found, then no style is attached to that feature.

Pseudocode for the logic:
`
foreach f in mvt_features: 
   foreach t in f.tags: 
      foreach s in json_styles: 
         if s.property == t.name and match(s,t.value): 
            apply_style(s,f)
`

**Comment by ZachTRice** [comment]
Current status:
When the schema type is `mapbox-gl-style`, the build will download and the json style files into a `vector_styles` folder, if the schema is `colormaps`, the xml files are downloaded into a `colormaps` folder and then the xml is parsed and converted to a json file. 

After processing / copying the files, the vector_style json folders get copied into the `web/config/vector_styles`, the colormaps  are put into the `web/config/palettes folder`.

The json files in these folders are then iterated over and attached to two separate `wv.config` objects, `config.palettes` & `config.vectorStyles`, via functions in in `web/js/palettes/palettes.js`

Next:
Ideally, I would want to either rename the `js/palettes` folder to something more generalized to describe colormap palettes and vector styles, or I will create a separate folder to house all the vector styling code. For now, we have the vectorStyles pulled in via a fairly clean manner which can be iterated over and used to style each type of feature attribute defined in the json style.

**Comment by ZachTRice** [comment]
When we tackle, "Implement method to change styling on the fly based on zoom level", we should look at other parts of the app, such as event tracks, to see if we can reuse this logic. Event tracks use vector lines which would look best if scaled with zoom (wider when zoomed in, thinner when zoomed out).

**Comment by ZachTRice** [comment]
Here is an example of what the FIRMS_MODIS_v6 mapbox-gl-style would look like:
```json
{
  "version": 8,
  "name": "FIRMS_MODIS_v6",
  "center": [0, 0],
  "zoom": 3,
  "sources": {
    "FIRMS_MODIS_v6": {
      "type": "vector",
      "tiles": [
      "https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/std/FIRMS_MODIS_v6/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.pbf",
      "https://sit.gibs.earthdata.nasa.gov/wmts/epsg4326/std/FIRMS_MODIS_v6/default/{Time}/{TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}.mvt"
      ],
      "maxzoom": 14
    }
  },
  "layers": [
    {
      "id": "MODIS_Low_Confidence_Fire_Points",
      "type": "fill",
      "source": "FIRMS_MODIS_v6",
      "filter": ["<=", "CONFIDENCE", 50],
      "paint": {
        "fill-color": "rgb(55,255,0)"
      }
    },
    {
      "id": "MODIS_Med_Confidence_Fire_Points",
      "type": "fill",
      "source": "FIRMS_MODIS_v6",
      "filter": [[">", "CONFIDENCE", 50], ["<=", "CONFIDENCE", 75]],
      "paint": {
        "fill-color": "rgb(255,128,0)"
      }
    },
    {
      "id": "MODIS_High_Confidence_Fire_Points",
      "type": "fill",
      "source": "FIRMS_MODIS_v6",
      "filter": [[">", "CONFIDENCE", 75], ["<=", "CONFIDENCE", 100]],
      "paint": {
        "fill-color": "rgb(255,0,0)"
      }
    }
  ]
}
```

**Comment by ZachTRice** [comment]
Our initial style JSON file for `OrbitTracks_Terra_Asc` had a regular expression for styling points based on time. It appears that regular expressions are not yet supported in the mapbox-gl-style spec. See: https://github.com/mapbox/mapbox-gl-js/issues/4089

**Comment by ZachTRice** [comment]
Our initial style JSON file for OrbitTracks_Terra_Asc had a regular expression for styling points based on time. It appears that regular expressions are not yet supported in the mapbox-gl-style spec. See: mapbox/mapbox-gl-js#4089

**Comment by mcechini** [comment]
Hmm, looks like they may be figuring out that regex thing, but not quick enough. Yeah, we can have "Minutes" and "Hours" attributes if we have to.
